### ISSUE TITLE
Dockerfile

### ISSUE THREAD

**Issue by 7ubi** [7ubi/Passwordmanager#1]
Create a Dockerimage for the forntend and backend.

**Comment by jabhishek87** [comment]
can i work on this

**Comment by 7ubi** [comment]
@jabhishek87 you can work on this. Just make a new Branch with an apropriate name and a pull request.

**Comment by Kalpesh-18** [comment]
Hey @7ubi , Can you please check #11 and let me know if you need any changes ✌️

**Comment by 7ubi** [comment]
@Kalpesh-18 I will review it when i get the time. I will let you know if I need you to make changes✌🏻
